USE [master]
GO

/****** Object:  Database [LOTR-game]    Script Date: 2019-01-09 14:46:15 ******/
CREATE DATABASE [LOTR-game]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LOTR-game', FILENAME = N'C:\Users\Administrator\LOTR-game.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LOTR-game_log', FILENAME = N'C:\Users\Administrator\LOTR-game_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [LOTR-game] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LOTR-game].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LOTR-game] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LOTR-game] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LOTR-game] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LOTR-game] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LOTR-game] SET ARITHABORT OFF 
GO

ALTER DATABASE [LOTR-game] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LOTR-game] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LOTR-game] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LOTR-game] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LOTR-game] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LOTR-game] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LOTR-game] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LOTR-game] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LOTR-game] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LOTR-game] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LOTR-game] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LOTR-game] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LOTR-game] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LOTR-game] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LOTR-game] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LOTR-game] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LOTR-game] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LOTR-game] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LOTR-game] SET  MULTI_USER 
GO

ALTER DATABASE [LOTR-game] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LOTR-game] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LOTR-game] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LOTR-game] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LOTR-game] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LOTR-game] SET QUERY_STORE = OFF
GO

USE [LOTR-game]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [LOTR-game] SET  READ_WRITE 
GO

